### ISSUE TITLE
IntroView Animation Issues

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#17]
IntroView 첫 번째 화면의 Animation 작업을 하고 있는데 Animation 적용 후 다운로드하여 실행해보니 잘 적용이 됨. 그러나 두 번째 실행부터는 이전으로 돌아가서 Animation을 확인해보니 동작하지 않는 이슈가 발생함

**Comment by sunhofficial** [comment]
인트로뷰에서 탭뷰 밑에 onchange이벤트를 넣어서 탭뷰가 바뀔때 isfirst를 true로 바꾸어주어 해결을 하였습니다.
