### ISSUE TITLE
AddMemberView Delete issue

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#4]
When we click Edit Button and Click Delete row that doesn't work. 
딜리트 버튼을 누르면 클릭이 되었다는 이벤트는 받지만 데이터 구조에서 사라지지 않고 계속 남아있는 현상 발생.

**Comment by ChangJin-Lee** [comment]
넵 확인했습니다. 코드를 확인했는데 이벤트 클릭도 현재 안되는 상황입니다. 관련해서 더 고민해야보아야 할 듯 합니다.

**Comment by ChangJin-Lee** [comment]
넵 확인했습니다. 코드를 확인했는데 이벤트 클릭도 현재 안되는 상황입니다. 관련해서 더 고민해야보아야 할 듯 합니다.

**Comment by ChangJin-Lee** [comment]
버튼을 드래그했을때 선택이되고 터치를 놓으면 정상적으로 삭제가 되는 것을 확인했습니다. onTapGesture 쪽이 문제인 것으로 판단됩니다.
