### ISSUE TITLE
refactor: refactoring IntroView

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#68]
- [x] IntroView 컨벤션 따라 수정
- [x] 코드 리팩토링
- [x] UserDefaults 코드 AppStorage로 변경
- [ ] ViewModel 분리
- [ ] view 레이아웃 수정

**Comment by ChangJin-Lee** [comment]
# Xcode Asset Naming에 대해 고민
 - 에셋 이름을 바꿔야하는데 이를 위한 기준이 필요.

**Comment by minnnidev** [comment]
> # Xcode Asset Naming에 대해 고민
> * 에셋 이름을 바꿔야하는데 이를 위한 기준이 필요.
> * sign에서 HandWithPhone으로 바꿨는데 어떤 기준으로 바꿨는지.

1. 인정
2. sign이 무슨 의미인지 모르겠어서 이미지에서 보이는대로 했어여
