### ISSUE TITLE
Xcode Asset Naming strategy

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#69]
TODO
- [x] Assets 뷰 별로 정리하기
- [x] Assets 이름 규칙에 따라 바꾸기

### 논의사항
프로젝트 내에 있는 에셋 이름 규칙

 ### 대안
 1. 기본적으로 lowercamelcase를 따른다.
 2. 에셋의 기능이 아닌 에셋 자체를 알려줘야한다.
 3. 에셋의 이름은 축약해선 안된다.
 4. 에셋의 이름은 같은데 사이즈가 다르다면 크기를 명시해줘야한다.

정답은 없으니 고민해봅시다.

**Comment by minnnidev** [comment]
## 정리
- 이미지 에셋 이름 전에 종류를 명시 img이름, btn이름
- 공통된 이미지는 Common 폴더에, 뷰별로 사용되는 이미지는 각 뷰 폴더에 위치

## 예시
- Asset 파일 폴더 구조
```
Common
ㄴ imgPearl
Login
ㄴ btnKakaoLogin
ㄴ btnAppleLogin
```

**Comment by ChangJin-Lee** [comment]
- 파이썬 코드로 Ssok 폴더를 모두 순회하며 파일의 이름. 파일 안의 해당하는 모든 단어를 바꿉니다.
    - 파일 내부의 단어를 바꾸는 함수인 replace_in_file 에서 코드 내의 단어를 바꾸고
    - 폴더와 파일 이름을 모두 바꾸는 replace_file_name 함수에서 폴더와 파일의 이름을 바꿉니다.
