### ISSUE TITLE
SwiftLint에서 excluded에 추가해도 line_length 경고 발생

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#76]
### 시도해본 github issue
- https://github.com/realm/SwiftLint/issues/3939
### 이슈 내용
- .swiftlint.yml 파일 excluded 부분에 Ssok/AppDelegate.swift을 추가.
-  그러나 line_length가 여전히 발생. 
 
### 시도해볼만한 것
- line_length 숫자를 크게하자.

**Comment by minnnidev** [comment]
@sunhofficial @pingse 
헬프.

**Comment by sunhofficial** [comment]
<img width="715" alt="스크린샷 2023-06-03 오전 12 11 30" src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/76695159/cc672073-48a9-49df-be11-32e31cac7df9">
이렇게 엔터하면 안생기는거 아닙니까? 
다른 문제인가요?

**Comment by minnnidev** [comment]
> <img alt="스크린샷 2023-06-03 오전 12 11 30" width="715" src="https://user-images.githubusercontent.com/76695159/242922821-cc672073-48a9-49df-be11-32e31cac7df9.png"> 이렇게 엔터하면 안생기는거 아닙니까? 다른 문제인가요?



이렇게 하면 해결돼여
근데 기본 함수 파라미터들을 저렇게 분리시키는 게 일반적인 건 아닌 것 같아서 애초에 AppDelegate 파일에는 swiftlint 적용을 안 하는 게 어떨까 싶었는데 그게 잘 안 되네여

**Comment by ChangJin-Lee** [comment]
정해야할듯합니다. 
1. line_length 크기를 늘린다.
2. @minnnidev 방법대로 한다.

**Comment by sunhofficial** [comment]
저거 하나때문에 line_length를 바꾸는 건 아닌거 같고 그냥 2를 좀더 찾아보는게 좋을거같아요

**Comment by pingse** [comment]
<img width="1009" alt="스크린샷 2023-06-03 오전 2 24 33" src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/54977093/a993372f-76b2-4537-9127-ffd1a4f88987">

저 부분을 없애버린 후에 excluded: 안에 Ssok/AppDelegate.swift를 넣어보니 정상적으로 예외처리가 되는 것을 확인했어요

**Comment by pingse** [comment]
![image](https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/54977093/e6dc9236-4d1c-4fd0-ad96-3faec209fc4a)

위 세개의 내용은 작성 참고용인 것 같아요
삭제하거나 주석처리를 하지 않으면 파일 전체에 swiftlint가 적용이 안되니 참고 부탁드립니다~

**Comment by ChangJin-Lee** [comment]
모두 해결했고 swiftlint 적용되었습니다.
