### ISSUE TITLE
strawView conflict error

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#8]
strawView에서 발생한 충돌을 해결합니다.

**Comment by ChangJin-Lee** [comment]
soda3 브랜치에서 에러를 해결하고 develop에 pull requests로 merge 해두었습니다.

**Comment by minnnidev** [comment]
> soda3 브랜치에서 에러를 해결하고 develop 브랜치에 pull requests로 merge 해두었습니다.

아직 안 햇어여.
