### ISSUE TITLE
refactor : refactoring BottleView

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#81]
- [x] 코드 리팩토링
- [x] ViewModel 분리 후 BottleView 삭제
- [x] StrawView에서 SpriteView사용

**Comment by pingse** [comment]
chore : delete BottleView and add BottleViewModel #81

**Comment by ChangJin-Lee** [comment]
작업 모두 완료 된건가요?

**Comment by pingse** [comment]
작업은 완료했는데 CJ가 맡으신 Lint부분 pr이 적용이 안되어있어서 일단 놔두고 있었어요

**Comment by ChangJin-Lee** [comment]
Lint부분 적용 해결했고 머지해두었습니다.
