### ISSUE TITLE
BottleViewModel의 벽면 위치 수정

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#92]
- TODO
- [x] BottleViewModel의 벽면 위치 수정

**Comment by pingse** [comment]
해결은 됐는데 그냥 싹 수정해서 올리려고 하는데 지금 xcode가 오류나서 다시 깔고있어요

**Comment by sunhofficial** [comment]
네 수정되면 다시알려주세요~

**Comment by pingse** [comment]
수정 다 했구요 strawview까지 수정해서 올렸어요 pr 받아줘요
