### ISSUE TITLE
NavigationStack관리

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#95]
## 📌 Issue
<!— 이슈에 대해 간략하게 설명해주세요 —>
전체적인 저희 앱의 flow를 어떻게 구성을 할지 생각해보아요. 어느쪽에서는 모달이 좋을 수도 있고 아니면 전체적으로 stack으로 쌓는 방법이 있을수도 있다고 생각합니다.

## 📝 To-do
<!— 진행할 작업에 대해 적어주세요 —>
- TODO
- [ ] strawView이후부터는 모달창으로 만들어보기 
- [ ] StrawView부터 navigationstack을 쌓기

**Comment by ChangJin-Lee** [comment]
해당내용 MissionEndingView 이후부터 모달 창으로 확정입니다.
