### ISSUE TITLE
Refactor view transition to modal

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#96]
## 📌 Issue

view transition 관리

## 📝 To-do

- [ ] 화면 전환 플로우 고민

**Comment by sunhofficial** [comment]
![IMG_2581](https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/76695159/559f6cb9-01db-429d-aad4-3d34b20720f0)
그런데 모달로 하게 되면 우리 스트로 뷰위에 모달로 올리는 거니까 이 펄 흔들리는 애들은 계속 뒤에서 작동하면서 각도에 따라 햅틱이 부르르 떨리지 않을까요?
