### ISSUE TITLE
미션 모델 수정

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#98]
## 📌 Issue
EndingView

## 📝 To-do
- TODO
- [x] 엔딩뷰 하나로 통합
- [x] 모델 짜기

**Comment by ChangJin-Lee** [comment]
해당 업무 develop branch에 merge 되었어요.

**Comment by ChangJin-Lee** [comment]
해당 업무 develop branch에 merge 되었어요.
